// Code generated by Gopapageno; DO NOT EDIT.
package main

import (
	"github.com/giornetta/gopapageno"
	"strings"
	"fmt"
	"os"
)

import (
	"math"
)

var parserInt64Pools []*gopapageno.Pool[int64]

// ParserPreallocMem initializes all the memory pools required by the semantic function of the parser.
func ParserPreallocMem(inputSize int, numThreads int) {
	parserInt64Pools = make([]*gopapageno.Pool[int64], numThreads)

	avgCharsPerNumber := float64(4)
	poolSizePerThread := int(math.Ceil((float64(inputSize) / avgCharsPerNumber) / float64(numThreads)))

	for i := 0; i < numThreads; i++ {
		parserInt64Pools[i] = gopapageno.NewPool[int64](poolSizePerThread)
	}
}


// Non-terminals
const (
	E = gopapageno.TokenEmpty + 1 + iota
	E_F_T
	E_T
	S
)

// Terminals
const (
	LPAR = gopapageno.TokenTerm + 1 + iota
	NUMBER
	PLUS
	RPAR
	TIMES
)

func DumpGraph[ValueType any](root *gopapageno.Token, f *os.File) {
	sb := strings.Builder{}
	sb.WriteString("digraph parse_tree {\n")
	sb.WriteString("ratio = fill;\n")
	sb.WriteString("node [style=filled];\n")

	var graphPrintRec func(t *gopapageno.Token, p *gopapageno.Token, sb *strings.Builder, i int)
	graphPrintRec = func(t *gopapageno.Token, p *gopapageno.Token, sb *strings.Builder, i int) {
		if t == nil {
			return
		}

		if p == nil {
			graphPrintRec(t.Child, t, sb, i+1)
			return
		}

		var t_name, t_color, p_name, p_color string

		switch p.Type {
		case E:
			p_name, p_color = "E", "0.408 0.498 1.000"
		case E_F_T:
			p_name, p_color = "E_F_T", "0.408 0.498 1.000"
		case E_T:
			p_name, p_color = "E_T", "0.408 0.498 1.000"
		case S:
			p_name, p_color = "S", "0.408 0.498 1.000"
		case gopapageno.TokenEmpty:
			p_name, p_color = "__EMPTY__", "0.408 0.498 1.000"
		case LPAR:
			p_name, p_color = "LPAR", "0.641 0.212 1.000"
		case NUMBER:
			p_name, p_color = "NUMBER", "0.641 0.212 1.000"
		case PLUS:
			p_name, p_color = "PLUS", "0.641 0.212 1.000"
		case RPAR:
			p_name, p_color = "RPAR", "0.641 0.212 1.000"
		case TIMES:
			p_name, p_color = "TIMES", "0.641 0.212 1.000"
		case gopapageno.TokenTerm:
			p_name, p_color = "__TERM__", "0.641 0.212 1.000"
		}

		switch t.Type {
		case E:
			t_name, t_color = "E", "0.408 0.498 1.000"
		case E_F_T:
			t_name, t_color = "E_F_T", "0.408 0.498 1.000"
		case E_T:
			t_name, t_color = "E_T", "0.408 0.498 1.000"
		case S:
			t_name, t_color = "S", "0.408 0.498 1.000"
		case gopapageno.TokenEmpty:
			t_name, t_color = "__EMPTY__", "0.408 0.498 1.000"
		case LPAR:
			t_name, t_color = "LPAR", "0.641 0.212 1.000"
		case NUMBER:
			t_name, t_color = "NUMBER", "0.641 0.212 1.000"
		case PLUS:
			t_name, t_color = "PLUS", "0.641 0.212 1.000"
		case RPAR:
			t_name, t_color = "RPAR", "0.641 0.212 1.000"
		case TIMES:
			t_name, t_color = "TIMES", "0.641 0.212 1.000"
		case gopapageno.TokenTerm:
			t_name, t_color = "__TERM__", "0.641 0.212 1.000"
		}

		sb.WriteString(fmt.Sprintf("\"%p\" -> \"%p\";\n", p, t))
		sb.WriteString(fmt.Sprintf("\"%p\" [label=\"%s\" color=\"%s\"];\n", p, p_name, p_color))
		sb.WriteString(fmt.Sprintf("\"%p\" [label=\"%s\" color=\"%s\"];\n", t, t_name, t_color))

		graphPrintRec(t.Child, t, sb, i+1)
		graphPrintRec(t.Next, p, sb, i)
	}
	graphPrintRec(root, nil, &sb, 0)
	sb.WriteString("}\n")

	fmt.Fprint(f, sb.String())
}


func SprintToken[ValueType any](root *gopapageno.Token) string {
	var sprintRec func(t *gopapageno.Token, sb *strings.Builder, indent string)

	sprintRec = func(t *gopapageno.Token, sb *strings.Builder, indent string) {
		if t == nil {
			return
		}

		sb.WriteString(indent)
		if t.Next == nil {
			sb.WriteString("└── ")
			indent += "    "
		} else {
			sb.WriteString("├── ")
			indent += "|   "
		}

		switch t.Type {
		case E:
			sb.WriteString("E")
		case E_F_T:
			sb.WriteString("E_F_T")
		case E_T:
			sb.WriteString("E_T")
		case S:
			sb.WriteString("S")
		case gopapageno.TokenEmpty:
			sb.WriteString("Empty")
		case LPAR:
			sb.WriteString("LPAR")
		case NUMBER:
			sb.WriteString("NUMBER")
		case PLUS:
			sb.WriteString("PLUS")
		case RPAR:
			sb.WriteString("RPAR")
		case TIMES:
			sb.WriteString("TIMES")
		case gopapageno.TokenTerm:
			sb.WriteString("Term")
		default:
			sb.WriteString("Unknown")
		}

		if t.Value != nil {
			if v, ok := any(t.Value).(*ValueType); ok {
				sb.WriteString(fmt.Sprintf(": %v", *v))
			} else {
				sb.WriteString(fmt.Sprintf("%v", v))
			}
		}
		
		sb.WriteString("\n")
		
		sprintRec(t.Child, sb, indent)
		sprintRec(t.Next, sb, indent[:len(indent)-4])
	}

	var sb strings.Builder
	
	sprintRec(root, &sb, "")
	
	return sb.String()
}

func NewGrammar() *gopapageno.Grammar {
	numTerminals := uint16(6)
	numNonTerminals := uint16(5)

	maxRHSLen := 3
	rules := []gopapageno.Rule{
		{S, []gopapageno.TokenType{E}, gopapageno.RuleSimple},
		{E, []gopapageno.TokenType{E, PLUS, E_F_T}, gopapageno.RuleSimple},
		{E, []gopapageno.TokenType{E, PLUS, E_T}, gopapageno.RuleSimple},
		{S, []gopapageno.TokenType{E_F_T}, gopapageno.RuleSimple},
		{E, []gopapageno.TokenType{E_F_T, PLUS, E_F_T}, gopapageno.RuleSimple},
		{E, []gopapageno.TokenType{E_F_T, PLUS, E_T}, gopapageno.RuleSimple},
		{E_T, []gopapageno.TokenType{E_F_T, TIMES, E_F_T}, gopapageno.RuleSimple},
		{S, []gopapageno.TokenType{E_T}, gopapageno.RuleSimple},
		{E, []gopapageno.TokenType{E_T, PLUS, E_F_T}, gopapageno.RuleSimple},
		{E, []gopapageno.TokenType{E_T, PLUS, E_T}, gopapageno.RuleSimple},
		{E_T, []gopapageno.TokenType{E_T, TIMES, E_F_T}, gopapageno.RuleSimple},
		{E_F_T, []gopapageno.TokenType{LPAR, E, RPAR}, gopapageno.RuleSimple},
		{E_F_T, []gopapageno.TokenType{LPAR, E_F_T, RPAR}, gopapageno.RuleSimple},
		{E_F_T, []gopapageno.TokenType{LPAR, E_T, RPAR}, gopapageno.RuleSimple},
		{E_F_T, []gopapageno.TokenType{NUMBER}, gopapageno.RuleSimple},
	}
	compressedRules := []uint16{0, 0, 5, 1, 13, 2, 31, 3, 59, 32769, 87, 32770, 120, 4, 0, 1, 32771, 18, 0, 0, 2, 2, 25, 3, 28, 1, 1, 0, 1, 2, 0, 4, 3, 2, 32771, 38, 32773, 51, 0, 0, 2, 2, 45, 3, 48, 1, 4, 0, 1, 5, 0, 0, 0, 1, 2, 56, 3, 6, 0, 4, 7, 2, 32771, 66, 32773, 79, 0, 0, 2, 2, 73, 3, 76, 1, 8, 0, 1, 9, 0, 0, 0, 1, 2, 84, 3, 10, 0, 0, 0, 3, 1, 96, 2, 104, 3, 112, 0, 0, 1, 32772, 101, 2, 11, 0, 0, 0, 1, 32772, 109, 2, 12, 0, 0, 0, 1, 32772, 117, 2, 13, 0, 2, 14, 0	}

	precMatrix := [][]gopapageno.Precedence{
		{gopapageno.PrecEquals, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields},
		{gopapageno.PrecTakes, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecEquals, gopapageno.PrecYields},
		{gopapageno.PrecTakes, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecTakes, gopapageno.PrecTakes, gopapageno.PrecTakes},
		{gopapageno.PrecTakes, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecTakes, gopapageno.PrecTakes, gopapageno.PrecYields},
		{gopapageno.PrecTakes, gopapageno.PrecEmpty, gopapageno.PrecEmpty, gopapageno.PrecTakes, gopapageno.PrecTakes, gopapageno.PrecTakes},
		{gopapageno.PrecTakes, gopapageno.PrecYields, gopapageno.PrecYields, gopapageno.PrecTakes, gopapageno.PrecTakes, gopapageno.PrecTakes},
	}
	bitPackedMatrix := []uint64{
		7674812621165782356, 169, 
	}

	fn := func(ruleDescription uint16, ruleFlags gopapageno.RuleFlags, lhs *gopapageno.Token, rhs []*gopapageno.Token, thread int){
		switch ruleDescription {
		case 0:
			S0 := lhs
			E1 := rhs[0]

			S0.Child = E1
			S0.LastChild = E1

			{
				S0.Value = E1.Value
			}
			_ = E1
		case 1:
			E0 := lhs
			E1 := rhs[0]
			PLUS2 := rhs[1]
			E_F_T3 := rhs[2]

			E0.Child = E1
			E1.Next = PLUS2
			PLUS2.Next = E_F_T3
			E0.LastChild = E_F_T3

			{
				newValue := parserInt64Pools[thread].Get()
				*newValue = *E1.Value.(*int64) + *E_F_T3.Value.(*int64)
				E0.Value = newValue
			}
			_ = E1
			_ = PLUS2
			_ = E_F_T3
		case 2:
			E0 := lhs
			E1 := rhs[0]
			PLUS2 := rhs[1]
			E_T3 := rhs[2]

			E0.Child = E1
			E1.Next = PLUS2
			PLUS2.Next = E_T3
			E0.LastChild = E_T3

			{
				newValue := parserInt64Pools[thread].Get()
				*newValue = *E1.Value.(*int64) + *E_T3.Value.(*int64)
				E0.Value = newValue
			}
			_ = E1
			_ = PLUS2
			_ = E_T3
		case 3:
			S0 := lhs
			E_F_T1 := rhs[0]

			S0.Child = E_F_T1
			S0.LastChild = E_F_T1

			{
				S0.Value = E_F_T1.Value
			}
			_ = E_F_T1
		case 4:
			E0 := lhs
			E_F_T1 := rhs[0]
			PLUS2 := rhs[1]
			E_F_T3 := rhs[2]

			E0.Child = E_F_T1
			E_F_T1.Next = PLUS2
			PLUS2.Next = E_F_T3
			E0.LastChild = E_F_T3

			{
				newValue := parserInt64Pools[thread].Get()
				*newValue = *E_F_T1.Value.(*int64) + *E_F_T3.Value.(*int64)
				E0.Value = newValue
			}
			_ = E_F_T1
			_ = PLUS2
			_ = E_F_T3
		case 5:
			E0 := lhs
			E_F_T1 := rhs[0]
			PLUS2 := rhs[1]
			E_T3 := rhs[2]

			E0.Child = E_F_T1
			E_F_T1.Next = PLUS2
			PLUS2.Next = E_T3
			E0.LastChild = E_T3

			{
				newValue := parserInt64Pools[thread].Get()
				*newValue = *E_F_T1.Value.(*int64) + *E_T3.Value.(*int64)
				E0.Value = newValue
			}
			_ = E_F_T1
			_ = PLUS2
			_ = E_T3
		case 6:
			E_T0 := lhs
			E_F_T1 := rhs[0]
			TIMES2 := rhs[1]
			E_F_T3 := rhs[2]

			E_T0.Child = E_F_T1
			E_F_T1.Next = TIMES2
			TIMES2.Next = E_F_T3
			E_T0.LastChild = E_F_T3

			{
			    newValue := parserInt64Pools[thread].Get()
			    *newValue = *E_F_T1.Value.(*int64) * *E_F_T3.Value.(*int64)
			    E_T0.Value = newValue
			}
			_ = E_F_T1
			_ = TIMES2
			_ = E_F_T3
		case 7:
			S0 := lhs
			E_T1 := rhs[0]

			S0.Child = E_T1
			S0.LastChild = E_T1

			{
				S0.Value = E_T1.Value
			}
			_ = E_T1
		case 8:
			E0 := lhs
			E_T1 := rhs[0]
			PLUS2 := rhs[1]
			E_F_T3 := rhs[2]

			E0.Child = E_T1
			E_T1.Next = PLUS2
			PLUS2.Next = E_F_T3
			E0.LastChild = E_F_T3

			{
				newValue := parserInt64Pools[thread].Get()
				*newValue = *E_T1.Value.(*int64) + *E_F_T3.Value.(*int64)
				E0.Value = newValue
			}
			_ = E_T1
			_ = PLUS2
			_ = E_F_T3
		case 9:
			E0 := lhs
			E_T1 := rhs[0]
			PLUS2 := rhs[1]
			E_T3 := rhs[2]

			E0.Child = E_T1
			E_T1.Next = PLUS2
			PLUS2.Next = E_T3
			E0.LastChild = E_T3

			{
				newValue := parserInt64Pools[thread].Get()
				*newValue = *E_T1.Value.(*int64) + *E_T3.Value.(*int64)
				E0.Value = newValue
			}
			_ = E_T1
			_ = PLUS2
			_ = E_T3
		case 10:
			E_T0 := lhs
			E_T1 := rhs[0]
			TIMES2 := rhs[1]
			E_F_T3 := rhs[2]

			E_T0.Child = E_T1
			E_T1.Next = TIMES2
			TIMES2.Next = E_F_T3
			E_T0.LastChild = E_F_T3

			{
			    newValue := parserInt64Pools[thread].Get()
			    *newValue = *E_T1.Value.(*int64) * *E_F_T3.Value.(*int64)
			    E_T0.Value = newValue
			}
			_ = E_T1
			_ = TIMES2
			_ = E_F_T3
		case 11:
			E_F_T0 := lhs
			LPAR1 := rhs[0]
			E2 := rhs[1]
			RPAR3 := rhs[2]

			E_F_T0.Child = LPAR1
			LPAR1.Next = E2
			E2.Next = RPAR3
			E_F_T0.LastChild = RPAR3

			{
				E_F_T0.Value = E2.Value
			}
			_ = LPAR1
			_ = E2
			_ = RPAR3
		case 12:
			E_F_T0 := lhs
			LPAR1 := rhs[0]
			E_F_T2 := rhs[1]
			RPAR3 := rhs[2]

			E_F_T0.Child = LPAR1
			LPAR1.Next = E_F_T2
			E_F_T2.Next = RPAR3
			E_F_T0.LastChild = RPAR3

			{
				E_F_T0.Value = E_F_T2.Value
			}
			_ = LPAR1
			_ = E_F_T2
			_ = RPAR3
		case 13:
			E_F_T0 := lhs
			LPAR1 := rhs[0]
			E_T2 := rhs[1]
			RPAR3 := rhs[2]

			E_F_T0.Child = LPAR1
			LPAR1.Next = E_T2
			E_T2.Next = RPAR3
			E_F_T0.LastChild = RPAR3

			{
				E_F_T0.Value = E_T2.Value
			}
			_ = LPAR1
			_ = E_T2
			_ = RPAR3
		case 14:
			E_F_T0 := lhs
			NUMBER1 := rhs[0]

			E_F_T0.Child = NUMBER1
			E_F_T0.LastChild = NUMBER1

			{
				E_F_T0.Value = NUMBER1.Value
			}
			_ = NUMBER1
		}
		_ = ruleFlags
	}

	return &gopapageno.Grammar{
		NumTerminals:  numTerminals,
		NumNonterminals: numNonTerminals,
		MaxRHSLength: maxRHSLen,
		Rules: rules,
		CompressedRules: compressedRules,
		PrecedenceMatrix: precMatrix,
		BitPackedPrecedenceMatrix: bitPackedMatrix,
		Func: fn,
		ParsingStrategy: gopapageno.OPP,
		PreambleFunc: ParserPreallocMem,
	}
}

